### ISSUE TITLE
[Feature]: Add a new  package named `logging` for Logging Configuration

### ISSUE THREAD

**Issue by lwpk110** [zncdatadev/operator-go#106]
### Duplicates

I have searched the existing issues

### Summary 💡

This issue proposes the creation of a new `logging` package that centralizes the configuration generation logic for logging frameworks such as log4j, log4j2, and vector. The goal is to standardize the way logging configurations are generated and applied across all operator products. This standardization will ensure consistent logging formats and streamline the integration of vector for log collection. The package will also serve as a foundation for future enhancements, such as adding utility functions to support the logging integration framework.

### Examples 🌈

todo..

### Motivation 🔦

The creation of a standardized framework package is motivated by the need to unify the logging configuration process across all operator products. By adhering to a consistent configuration generation standard, we can ensure that logs are collected and formatted uniformly, which is critical for effective monitoring and debugging. Additionally, this package will reduce redundancy and make it easier to manage and update logging configurations across different projects. As a result, the overall efficiency and maintainability of our logging infrastructure will be significantly improved.

**Comment by lwpk110** [comment]
@whg517 review it

**Comment by whg517** [comment]
@lwpk110 LSTM

The name of the logging package is ambiguous, generally for the logging framework configuration and related design of the current language. If you want to provide a differentiated logging configuration (log4j,log4j2, vector) for production applications to implement log collection functionality, I think you can call it product_logging, or something more appropriate.
