### ISSUE TITLE
[Feature]: Extract common utils and pkgs from practical developed operators

### ISSUE THREAD

**Issue by lwpk110** [zncdatadev/operator-go#27]
After developing several operators, we have accumulated some experience, so at this time, we need to extract some common tools and pkgs from the operators we have developed in practice.

The following task list will be  updated continuously:

- [ ] #29
- [x] #28
- [x] #30
- [x] #31
- [ ] #32
- [ ] #33
- [ ] #34

**Comment by whg517** [comment]
LGTM, Should we split the issure into functional units and associate them with the specified PR? In addition, the name should indicate the specific function implemented rather than using a generic name for a task that appears to have no end in time.

**Comment by whg517** [comment]
I think we can proceed from three units:

- util package or other helper tools , maybe other naming 
- kds develop framework
- commonly api struct 

Each unit has at least one todo.

You can split these into multiple issues.

**Comment by lwpk110** [comment]
yes, you are right. I wonder if this issue is necessary? It is not a specific executable issue. Rather, it serves as a catalog role of collected all issues for this extraction. When all split issues are resolved, we finally close it
